apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - rbac.yaml
  - operator.yaml
  # Uncomment after creating the sealed secret
  # - oauth-secret-sealed.yaml
  - argocd-tailscale-service.yaml
