apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: household-task-manager

bases:
  - ../../base

resources:
  - ingress.yaml

patchesStrategicMerge:
  - patches/replicas.yaml

images:
  - name: ghcr.io/kamegrueon/household-task-manager-backend
    newTag: main
  - name: ghcr.io/kamegrueon/household-task-manager-frontend
    newTag: main
